/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CrosschainMessagerInterface extends ethers.utils.Interface {
  functions: {
    "handle(uint32,bytes32,bytes)": FunctionFragment;
    "lastMessage()": FunctionFragment;
    "lastSender()": FunctionFragment;
    "sendString(uint32,bytes32,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "handle",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendString",
    values: [BigNumberish, BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "handle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastSender", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sendString", data: BytesLike): Result;

  events: {
    "ReceivedMessage(bytes,uint32,bytes32)": EventFragment;
    "SentMessage(uint32,bytes32,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ReceivedMessage"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SentMessage"): EventFragment;
}

export type ReceivedMessageEvent = TypedEvent<
  [string, number, string] & { message: string; origin: number; sender: string }
>;

export type SentMessageEvent = TypedEvent<
  [number, string, string] & {
    destinationDomain: number;
    recipient: string;
    message: string;
  }
>;

export class CrosschainMessager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CrosschainMessagerInterface;

  functions: {
    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lastMessage(overrides?: CallOverrides): Promise<[string]>;

    lastSender(overrides?: CallOverrides): Promise<[string]>;

    sendString(
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  handle(
    _origin: BigNumberish,
    _sender: BytesLike,
    _message: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lastMessage(overrides?: CallOverrides): Promise<string>;

  lastSender(overrides?: CallOverrides): Promise<string>;

  sendString(
    _destinationDomain: BigNumberish,
    _recipient: BytesLike,
    _message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _message: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    lastMessage(overrides?: CallOverrides): Promise<string>;

    lastSender(overrides?: CallOverrides): Promise<string>;

    sendString(
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ReceivedMessage(bytes,uint32,bytes32)"(
      message?: BytesLike | null,
      origin?: null,
      sender?: null
    ): TypedEventFilter<
      [string, number, string],
      { message: string; origin: number; sender: string }
    >;

    ReceivedMessage(
      message?: BytesLike | null,
      origin?: null,
      sender?: null
    ): TypedEventFilter<
      [string, number, string],
      { message: string; origin: number; sender: string }
    >;

    "SentMessage(uint32,bytes32,string)"(
      destinationDomain?: null,
      recipient?: null,
      message?: null
    ): TypedEventFilter<
      [number, string, string],
      { destinationDomain: number; recipient: string; message: string }
    >;

    SentMessage(
      destinationDomain?: null,
      recipient?: null,
      message?: null
    ): TypedEventFilter<
      [number, string, string],
      { destinationDomain: number; recipient: string; message: string }
    >;
  };

  estimateGas: {
    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lastMessage(overrides?: CallOverrides): Promise<BigNumber>;

    lastSender(overrides?: CallOverrides): Promise<BigNumber>;

    sendString(
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lastMessage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sendString(
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
