/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HyperlaneMessageSenderInterface extends ethers.utils.Interface {
  functions: {
    "sendString(uint32,bytes32,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "sendString",
    values: [BigNumberish, BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "sendString", data: BytesLike): Result;

  events: {
    "SentMessage(uint32,bytes32,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SentMessage"): EventFragment;
}

export type SentMessageEvent = TypedEvent<
  [number, string, string] & {
    destinationDomain: number;
    recipient: string;
    message: string;
  }
>;

export class HyperlaneMessageSender extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HyperlaneMessageSenderInterface;

  functions: {
    sendString(
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  sendString(
    _destinationDomain: BigNumberish,
    _recipient: BytesLike,
    _message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    sendString(
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SentMessage(uint32,bytes32,string)"(
      destinationDomain?: null,
      recipient?: null,
      message?: null
    ): TypedEventFilter<
      [number, string, string],
      { destinationDomain: number; recipient: string; message: string }
    >;

    SentMessage(
      destinationDomain?: null,
      recipient?: null,
      message?: null
    ): TypedEventFilter<
      [number, string, string],
      { destinationDomain: number; recipient: string; message: string }
    >;
  };

  estimateGas: {
    sendString(
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    sendString(
      _destinationDomain: BigNumberish,
      _recipient: BytesLike,
      _message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
