/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HyperlaneMessageReceiverInterface extends ethers.utils.Interface {
  functions: {
    "handle(uint32,bytes32,bytes)": FunctionFragment;
    "lastMessage()": FunctionFragment;
    "lastSender()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "handle",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastSender",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "handle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastSender", data: BytesLike): Result;

  events: {
    "ReceivedMessage(uint32,bytes32,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ReceivedMessage"): EventFragment;
}

export type ReceivedMessageEvent = TypedEvent<
  [number, string, string] & { origin: number; sender: string; message: string }
>;

export class HyperlaneMessageReceiver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HyperlaneMessageReceiverInterface;

  functions: {
    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lastMessage(overrides?: CallOverrides): Promise<[string]>;

    lastSender(overrides?: CallOverrides): Promise<[string]>;
  };

  handle(
    _origin: BigNumberish,
    _sender: BytesLike,
    _message: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lastMessage(overrides?: CallOverrides): Promise<string>;

  lastSender(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _message: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    lastMessage(overrides?: CallOverrides): Promise<string>;

    lastSender(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ReceivedMessage(uint32,bytes32,bytes)"(
      origin?: null,
      sender?: null,
      message?: null
    ): TypedEventFilter<
      [number, string, string],
      { origin: number; sender: string; message: string }
    >;

    ReceivedMessage(
      origin?: null,
      sender?: null,
      message?: null
    ): TypedEventFilter<
      [number, string, string],
      { origin: number; sender: string; message: string }
    >;
  };

  estimateGas: {
    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lastMessage(overrides?: CallOverrides): Promise<BigNumber>;

    lastSender(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lastMessage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
