/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MockMailboxInterface extends ethers.utils.Interface {
  functions: {
    "VERSION()": FunctionFragment;
    "addInboundMessage(bytes)": FunctionFragment;
    "addRemoteMailbox(uint32,address)": FunctionFragment;
    "defaultHook()": FunctionFragment;
    "defaultIsm()": FunctionFragment;
    "delivered(bytes32)": FunctionFragment;
    "deployedBlock()": FunctionFragment;
    "dispatch(uint32,bytes32,bytes,bytes,address)": FunctionFragment;
    "inboundMessages(uint256)": FunctionFragment;
    "inboundProcessedNonce()": FunctionFragment;
    "inboundUnprocessedNonce()": FunctionFragment;
    "initialize(address,address,address,address)": FunctionFragment;
    "latestDispatchedId()": FunctionFragment;
    "localDomain()": FunctionFragment;
    "nonce()": FunctionFragment;
    "owner()": FunctionFragment;
    "process(bytes,bytes)": FunctionFragment;
    "processNextInboundMessage()": FunctionFragment;
    "processedAt(bytes32)": FunctionFragment;
    "processor(bytes32)": FunctionFragment;
    "quoteDispatch(uint32,bytes32,bytes,bytes,address)": FunctionFragment;
    "recipientIsm(address)": FunctionFragment;
    "remoteMailboxes(uint32)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "requiredHook()": FunctionFragment;
    "setDefaultHook(address)": FunctionFragment;
    "setDefaultIsm(address)": FunctionFragment;
    "setRequiredHook(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addInboundMessage",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addRemoteMailbox",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultHook",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defaultIsm",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delivered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dispatch",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "inboundMessages",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "inboundProcessedNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "inboundUnprocessedNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "latestDispatchedId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "process",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processNextInboundMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processedAt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processor",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteDispatch",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recipientIsm",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "remoteMailboxes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requiredHook",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultHook",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultIsm",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequiredHook",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addInboundMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRemoteMailbox",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "defaultIsm", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delivered", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployedBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dispatch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "inboundMessages",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inboundProcessedNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "inboundUnprocessedNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestDispatchedId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "process", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processNextInboundMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "processor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteDispatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recipientIsm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remoteMailboxes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultIsm",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRequiredHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "DefaultHookSet(address)": EventFragment;
    "DefaultIsmSet(address)": EventFragment;
    "Dispatch(address,uint32,bytes32,bytes)": EventFragment;
    "DispatchId(bytes32)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "Process(uint32,bytes32,address)": EventFragment;
    "ProcessId(bytes32)": EventFragment;
    "RequiredHookSet(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DefaultHookSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DefaultIsmSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Dispatch"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DispatchId"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Process"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProcessId"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequiredHookSet"): EventFragment;
}

export type DefaultHookSetEvent = TypedEvent<[string] & { hook: string }>;

export type DefaultIsmSetEvent = TypedEvent<[string] & { module: string }>;

export type DispatchEvent = TypedEvent<
  [string, number, string, string] & {
    sender: string;
    destination: number;
    recipient: string;
    message: string;
  }
>;

export type DispatchIdEvent = TypedEvent<[string] & { messageId: string }>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type ProcessEvent = TypedEvent<
  [number, string, string] & {
    origin: number;
    sender: string;
    recipient: string;
  }
>;

export type ProcessIdEvent = TypedEvent<[string] & { messageId: string }>;

export type RequiredHookSetEvent = TypedEvent<[string] & { hook: string }>;

export class MockMailbox extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MockMailboxInterface;

  functions: {
    VERSION(overrides?: CallOverrides): Promise<[number]>;

    addInboundMessage(
      message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addRemoteMailbox(
      _domain: BigNumberish,
      _mailbox: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    defaultHook(overrides?: CallOverrides): Promise<[string]>;

    defaultIsm(overrides?: CallOverrides): Promise<[string]>;

    delivered(_id: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    deployedBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    "dispatch(uint32,bytes32,bytes,bytes,address)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "dispatch(uint32,bytes32,bytes,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      hookMetadata: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "dispatch(uint32,bytes32,bytes)"(
      _destinationDomain: BigNumberish,
      _recipientAddress: BytesLike,
      _messageBody: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    inboundMessages(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    inboundProcessedNonce(overrides?: CallOverrides): Promise<[number]>;

    inboundUnprocessedNonce(overrides?: CallOverrides): Promise<[number]>;

    initialize(
      _owner: string,
      _defaultIsm: string,
      _defaultHook: string,
      _requiredHook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    latestDispatchedId(overrides?: CallOverrides): Promise<[string]>;

    localDomain(overrides?: CallOverrides): Promise<[number]>;

    nonce(overrides?: CallOverrides): Promise<[number]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    process(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    processNextInboundMessage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    processedAt(_id: BytesLike, overrides?: CallOverrides): Promise<[number]>;

    processor(_id: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "quoteDispatch(uint32,bytes32,bytes,bytes,address)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fee: BigNumber }>;

    "quoteDispatch(uint32,bytes32,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fee: BigNumber }>;

    "quoteDispatch(uint32,bytes32,bytes,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      defaultHookMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fee: BigNumber }>;

    recipientIsm(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    remoteMailboxes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requiredHook(overrides?: CallOverrides): Promise<[string]>;

    setDefaultHook(
      _hook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDefaultIsm(
      _module: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setRequiredHook(
      _hook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  VERSION(overrides?: CallOverrides): Promise<number>;

  addInboundMessage(
    message: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addRemoteMailbox(
    _domain: BigNumberish,
    _mailbox: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  defaultHook(overrides?: CallOverrides): Promise<string>;

  defaultIsm(overrides?: CallOverrides): Promise<string>;

  delivered(_id: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  deployedBlock(overrides?: CallOverrides): Promise<BigNumber>;

  "dispatch(uint32,bytes32,bytes,bytes,address)"(
    destinationDomain: BigNumberish,
    recipientAddress: BytesLike,
    messageBody: BytesLike,
    metadata: BytesLike,
    hook: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "dispatch(uint32,bytes32,bytes,bytes)"(
    destinationDomain: BigNumberish,
    recipientAddress: BytesLike,
    messageBody: BytesLike,
    hookMetadata: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "dispatch(uint32,bytes32,bytes)"(
    _destinationDomain: BigNumberish,
    _recipientAddress: BytesLike,
    _messageBody: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  inboundMessages(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  inboundProcessedNonce(overrides?: CallOverrides): Promise<number>;

  inboundUnprocessedNonce(overrides?: CallOverrides): Promise<number>;

  initialize(
    _owner: string,
    _defaultIsm: string,
    _defaultHook: string,
    _requiredHook: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  latestDispatchedId(overrides?: CallOverrides): Promise<string>;

  localDomain(overrides?: CallOverrides): Promise<number>;

  nonce(overrides?: CallOverrides): Promise<number>;

  owner(overrides?: CallOverrides): Promise<string>;

  process(
    _metadata: BytesLike,
    _message: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  processNextInboundMessage(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  processedAt(_id: BytesLike, overrides?: CallOverrides): Promise<number>;

  processor(_id: BytesLike, overrides?: CallOverrides): Promise<string>;

  "quoteDispatch(uint32,bytes32,bytes,bytes,address)"(
    destinationDomain: BigNumberish,
    recipientAddress: BytesLike,
    messageBody: BytesLike,
    metadata: BytesLike,
    hook: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "quoteDispatch(uint32,bytes32,bytes)"(
    destinationDomain: BigNumberish,
    recipientAddress: BytesLike,
    messageBody: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "quoteDispatch(uint32,bytes32,bytes,bytes)"(
    destinationDomain: BigNumberish,
    recipientAddress: BytesLike,
    messageBody: BytesLike,
    defaultHookMetadata: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  recipientIsm(_recipient: string, overrides?: CallOverrides): Promise<string>;

  remoteMailboxes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requiredHook(overrides?: CallOverrides): Promise<string>;

  setDefaultHook(
    _hook: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDefaultIsm(
    _module: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setRequiredHook(
    _hook: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    VERSION(overrides?: CallOverrides): Promise<number>;

    addInboundMessage(
      message: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    addRemoteMailbox(
      _domain: BigNumberish,
      _mailbox: string,
      overrides?: CallOverrides
    ): Promise<void>;

    defaultHook(overrides?: CallOverrides): Promise<string>;

    defaultIsm(overrides?: CallOverrides): Promise<string>;

    delivered(_id: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    deployedBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "dispatch(uint32,bytes32,bytes,bytes,address)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "dispatch(uint32,bytes32,bytes,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      hookMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "dispatch(uint32,bytes32,bytes)"(
      _destinationDomain: BigNumberish,
      _recipientAddress: BytesLike,
      _messageBody: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    inboundMessages(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    inboundProcessedNonce(overrides?: CallOverrides): Promise<number>;

    inboundUnprocessedNonce(overrides?: CallOverrides): Promise<number>;

    initialize(
      _owner: string,
      _defaultIsm: string,
      _defaultHook: string,
      _requiredHook: string,
      overrides?: CallOverrides
    ): Promise<void>;

    latestDispatchedId(overrides?: CallOverrides): Promise<string>;

    localDomain(overrides?: CallOverrides): Promise<number>;

    nonce(overrides?: CallOverrides): Promise<number>;

    owner(overrides?: CallOverrides): Promise<string>;

    process(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    processNextInboundMessage(overrides?: CallOverrides): Promise<void>;

    processedAt(_id: BytesLike, overrides?: CallOverrides): Promise<number>;

    processor(_id: BytesLike, overrides?: CallOverrides): Promise<string>;

    "quoteDispatch(uint32,bytes32,bytes,bytes,address)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "quoteDispatch(uint32,bytes32,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "quoteDispatch(uint32,bytes32,bytes,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      defaultHookMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recipientIsm(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<string>;

    remoteMailboxes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    requiredHook(overrides?: CallOverrides): Promise<string>;

    setDefaultHook(_hook: string, overrides?: CallOverrides): Promise<void>;

    setDefaultIsm(_module: string, overrides?: CallOverrides): Promise<void>;

    setRequiredHook(_hook: string, overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DefaultHookSet(address)"(
      hook?: string | null
    ): TypedEventFilter<[string], { hook: string }>;

    DefaultHookSet(
      hook?: string | null
    ): TypedEventFilter<[string], { hook: string }>;

    "DefaultIsmSet(address)"(
      module?: string | null
    ): TypedEventFilter<[string], { module: string }>;

    DefaultIsmSet(
      module?: string | null
    ): TypedEventFilter<[string], { module: string }>;

    "Dispatch(address,uint32,bytes32,bytes)"(
      sender?: string | null,
      destination?: BigNumberish | null,
      recipient?: BytesLike | null,
      message?: null
    ): TypedEventFilter<
      [string, number, string, string],
      {
        sender: string;
        destination: number;
        recipient: string;
        message: string;
      }
    >;

    Dispatch(
      sender?: string | null,
      destination?: BigNumberish | null,
      recipient?: BytesLike | null,
      message?: null
    ): TypedEventFilter<
      [string, number, string, string],
      {
        sender: string;
        destination: number;
        recipient: string;
        message: string;
      }
    >;

    "DispatchId(bytes32)"(
      messageId?: BytesLike | null
    ): TypedEventFilter<[string], { messageId: string }>;

    DispatchId(
      messageId?: BytesLike | null
    ): TypedEventFilter<[string], { messageId: string }>;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "Process(uint32,bytes32,address)"(
      origin?: BigNumberish | null,
      sender?: BytesLike | null,
      recipient?: string | null
    ): TypedEventFilter<
      [number, string, string],
      { origin: number; sender: string; recipient: string }
    >;

    Process(
      origin?: BigNumberish | null,
      sender?: BytesLike | null,
      recipient?: string | null
    ): TypedEventFilter<
      [number, string, string],
      { origin: number; sender: string; recipient: string }
    >;

    "ProcessId(bytes32)"(
      messageId?: BytesLike | null
    ): TypedEventFilter<[string], { messageId: string }>;

    ProcessId(
      messageId?: BytesLike | null
    ): TypedEventFilter<[string], { messageId: string }>;

    "RequiredHookSet(address)"(
      hook?: string | null
    ): TypedEventFilter<[string], { hook: string }>;

    RequiredHookSet(
      hook?: string | null
    ): TypedEventFilter<[string], { hook: string }>;
  };

  estimateGas: {
    VERSION(overrides?: CallOverrides): Promise<BigNumber>;

    addInboundMessage(
      message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addRemoteMailbox(
      _domain: BigNumberish,
      _mailbox: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    defaultHook(overrides?: CallOverrides): Promise<BigNumber>;

    defaultIsm(overrides?: CallOverrides): Promise<BigNumber>;

    delivered(_id: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    deployedBlock(overrides?: CallOverrides): Promise<BigNumber>;

    "dispatch(uint32,bytes32,bytes,bytes,address)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "dispatch(uint32,bytes32,bytes,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      hookMetadata: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "dispatch(uint32,bytes32,bytes)"(
      _destinationDomain: BigNumberish,
      _recipientAddress: BytesLike,
      _messageBody: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    inboundMessages(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    inboundProcessedNonce(overrides?: CallOverrides): Promise<BigNumber>;

    inboundUnprocessedNonce(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _owner: string,
      _defaultIsm: string,
      _defaultHook: string,
      _requiredHook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    latestDispatchedId(overrides?: CallOverrides): Promise<BigNumber>;

    localDomain(overrides?: CallOverrides): Promise<BigNumber>;

    nonce(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    process(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    processNextInboundMessage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    processedAt(_id: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    processor(_id: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "quoteDispatch(uint32,bytes32,bytes,bytes,address)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "quoteDispatch(uint32,bytes32,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "quoteDispatch(uint32,bytes32,bytes,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      defaultHookMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recipientIsm(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    remoteMailboxes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requiredHook(overrides?: CallOverrides): Promise<BigNumber>;

    setDefaultHook(
      _hook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDefaultIsm(
      _module: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setRequiredHook(
      _hook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    VERSION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addInboundMessage(
      message: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addRemoteMailbox(
      _domain: BigNumberish,
      _mailbox: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    defaultHook(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    defaultIsm(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delivered(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deployedBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "dispatch(uint32,bytes32,bytes,bytes,address)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "dispatch(uint32,bytes32,bytes,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      hookMetadata: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "dispatch(uint32,bytes32,bytes)"(
      _destinationDomain: BigNumberish,
      _recipientAddress: BytesLike,
      _messageBody: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    inboundMessages(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inboundProcessedNonce(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    inboundUnprocessedNonce(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _owner: string,
      _defaultIsm: string,
      _defaultHook: string,
      _requiredHook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    latestDispatchedId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    localDomain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonce(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    process(
      _metadata: BytesLike,
      _message: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    processNextInboundMessage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    processedAt(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    processor(
      _id: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "quoteDispatch(uint32,bytes32,bytes,bytes,address)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      metadata: BytesLike,
      hook: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "quoteDispatch(uint32,bytes32,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "quoteDispatch(uint32,bytes32,bytes,bytes)"(
      destinationDomain: BigNumberish,
      recipientAddress: BytesLike,
      messageBody: BytesLike,
      defaultHookMetadata: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recipientIsm(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    remoteMailboxes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requiredHook(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setDefaultHook(
      _hook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDefaultIsm(
      _module: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setRequiredHook(
      _hook: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
