/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TestRecipientInterface extends ethers.utils.Interface {
  functions: {
    "fooBar(uint256,string)": FunctionFragment;
    "handle(uint32,bytes32,bytes)": FunctionFragment;
    "interchainSecurityModule()": FunctionFragment;
    "lastCallMessage()": FunctionFragment;
    "lastCaller()": FunctionFragment;
    "lastData()": FunctionFragment;
    "lastSender()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setInterchainSecurityModule(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "fooBar",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "handle",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "interchainSecurityModule",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastCallMessage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastCaller",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lastData", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lastSender",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setInterchainSecurityModule",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "fooBar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "handle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "interchainSecurityModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastCallMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lastCaller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastData", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lastSender", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInterchainSecurityModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "ReceivedCall(address,uint256,string)": EventFragment;
    "ReceivedMessage(uint32,bytes32,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceivedCall"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReceivedMessage"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type ReceivedCallEvent = TypedEvent<
  [string, BigNumber, string] & {
    caller: string;
    amount: BigNumber;
    message: string;
  }
>;

export type ReceivedMessageEvent = TypedEvent<
  [number, string, BigNumber, string] & {
    origin: number;
    sender: string;
    value: BigNumber;
    message: string;
  }
>;

export class TestRecipient extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestRecipientInterface;

  functions: {
    fooBar(
      amount: BigNumberish,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    interchainSecurityModule(overrides?: CallOverrides): Promise<[string]>;

    lastCallMessage(overrides?: CallOverrides): Promise<[string]>;

    lastCaller(overrides?: CallOverrides): Promise<[string]>;

    lastData(overrides?: CallOverrides): Promise<[string]>;

    lastSender(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setInterchainSecurityModule(
      _ism: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  fooBar(
    amount: BigNumberish,
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  handle(
    _origin: BigNumberish,
    _sender: BytesLike,
    _data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  interchainSecurityModule(overrides?: CallOverrides): Promise<string>;

  lastCallMessage(overrides?: CallOverrides): Promise<string>;

  lastCaller(overrides?: CallOverrides): Promise<string>;

  lastData(overrides?: CallOverrides): Promise<string>;

  lastSender(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setInterchainSecurityModule(
    _ism: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    fooBar(
      amount: BigNumberish,
      message: string,
      overrides?: CallOverrides
    ): Promise<void>;

    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    interchainSecurityModule(overrides?: CallOverrides): Promise<string>;

    lastCallMessage(overrides?: CallOverrides): Promise<string>;

    lastCaller(overrides?: CallOverrides): Promise<string>;

    lastData(overrides?: CallOverrides): Promise<string>;

    lastSender(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setInterchainSecurityModule(
      _ism: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "ReceivedCall(address,uint256,string)"(
      caller?: string | null,
      amount?: null,
      message?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { caller: string; amount: BigNumber; message: string }
    >;

    ReceivedCall(
      caller?: string | null,
      amount?: null,
      message?: null
    ): TypedEventFilter<
      [string, BigNumber, string],
      { caller: string; amount: BigNumber; message: string }
    >;

    "ReceivedMessage(uint32,bytes32,uint256,string)"(
      origin?: BigNumberish | null,
      sender?: BytesLike | null,
      value?: BigNumberish | null,
      message?: null
    ): TypedEventFilter<
      [number, string, BigNumber, string],
      { origin: number; sender: string; value: BigNumber; message: string }
    >;

    ReceivedMessage(
      origin?: BigNumberish | null,
      sender?: BytesLike | null,
      value?: BigNumberish | null,
      message?: null
    ): TypedEventFilter<
      [number, string, BigNumber, string],
      { origin: number; sender: string; value: BigNumber; message: string }
    >;
  };

  estimateGas: {
    fooBar(
      amount: BigNumberish,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    interchainSecurityModule(overrides?: CallOverrides): Promise<BigNumber>;

    lastCallMessage(overrides?: CallOverrides): Promise<BigNumber>;

    lastCaller(overrides?: CallOverrides): Promise<BigNumber>;

    lastData(overrides?: CallOverrides): Promise<BigNumber>;

    lastSender(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setInterchainSecurityModule(
      _ism: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    fooBar(
      amount: BigNumberish,
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    handle(
      _origin: BigNumberish,
      _sender: BytesLike,
      _data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    interchainSecurityModule(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastCallMessage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastCaller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setInterchainSecurityModule(
      _ism: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
